#ifndef LOGS_LIBRARY_GLOBAL_H
#define LOGS_LIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LOGS_LIBRARY_LIBRARY)
#  define LOGS_LIBRARY_EXPORT Q_DECL_EXPORT
#else
#  define LOGS_LIBRARY_EXPORT Q_DECL_IMPORT
#endif

#endif // LOGS_LIBRARY_GLOBAL_H
